Repository debionetwork/debio-node, pull requests merged in 2021-11, with the labels that each got.

#114 ci: use bastion for deploy
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#115 fix: types.json
  types.json
Labels: bug

#116 refactor: development chainspec.
  node/src/chain_spec.rs
Labels: bug

#118 feat: implement weights for user-profile pallet.
  Cargo.lock
  pallets/user-profile/src/lib.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#119 feat: implement weights on lab pallet.
  Makefile
  pallets/labs/src/lib.rs
  pallets/labs/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
  runtime/src/weights/labs.rs
  types.json
Labels: enhancement

#122 feat: get lab verification status.
  pallets/labs/src/interface.rs
  pallets/labs/src/lib.rs
Labels: enhancement

#123 feat: new dna collection field.
  pallets/genetic-testing/benchmarking/src/lib.rs
  pallets/orders/benchmarking/src/lib.rs
  pallets/services/benchmarking/src/lib.rs
  pallets/services/src/lib.rs
Labels: enhancement

#124 feat: implement weights in doctor pallet.
  pallets/doctors/src/lib.rs
  pallets/doctors/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#125 feat: implement weights in genetic testing pallet.
  pallets/genetic-testing/src/lib.rs
  pallets/genetic-testing/src/weights.rs
  runtime/src/lib.rs
  runtime/src/weights/genetic_testing.rs
Labels: enhancement

#126 feat: implements weights in hospital pallet.
  pallets/hospitals/src/lib.rs
  pallets/hospitals/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#127 feat: implement weights on doctor certification pallet.
  pallets/doctor-certifications/src/lib.rs
  pallets/doctor-certifications/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#128 feat: implement weights in services pallet.
  pallets/services/src/lib.rs
  pallets/services/src/weights.rs
  runtime/src/lib.rs
  runtime/src/weights/services.rs
Labels: enhancement

#134 ci: connect to kubernetes cluster
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#132 feat: implement weights in orders pallet.
  pallets/orders/src/lib.rs
  pallets/orders/src/weights.rs
  runtime/src/lib.rs
  runtime/src/weights/orders.rs
Labels: enhancement

#131 feat: implement weights on hospital certifications pallet.
  pallets/hospital-certifications/src/lib.rs
  pallets/hospital-certifications/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#130 feat: implement weights in emr pallet.
  pallets/electronic-medical-record/src/lib.rs
  pallets/electronic-medical-record/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement

#129 feat: benchmark default substrate pallets.
  runtime/src/lib.rs
  runtime/src/weights/frame_system.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_assets.rs
  runtime/src/weights/pallet_balances.rs
  runtime/src/weights/pallet_im_online.rs
  runtime/src/weights/pallet_timestamp.rs
Labels: enhancement

#133 fix: slash funds.
  pallets/rewards/src/lib.rs
Labels: enhancement

#136 feat: allow adding multiple EMRs.
  pallets/electronic-medical-record/src/benchmarking.rs
  pallets/electronic-medical-record/src/interface.rs
  pallets/electronic-medical-record/src/lib.rs
  pallets/electronic-medical-record/src/weights.rs
  traits/electronic-medical-record/src/lib.rs
Labels: enhancement, tests

#142 ci: cleaning
  .github/workflows/beta.yml
  .github/workflows/main.yml
Labels: CI

#143 ci: fixed typo
  .github/workflows/main.yml
Labels: CI

#146 fixed pallet service request
  pallets/service-request/src/lib.rs
  runtime/src/lib.rs
Labels: Improvement

#145 fix: removed warnings.
  pallets/doctors/src/lib.rs
  pallets/electronic-medical-record/src/lib.rs
  pallets/hospitals/src/lib.rs
  pallets/labs/src/lib.rs
Labels: bug, Improvement

#147 fix: show types in chain state
  Cargo.lock
  pallets/certifications/benchmarking/Cargo.toml
  pallets/certifications/benchmarking/src/lib.rs
  pallets/doctor-certifications/Cargo.toml
  pallets/doctor-certifications/benchmarking/Cargo.toml
  pallets/doctor-certifications/benchmarking/src/lib.rs
  pallets/doctors/Cargo.toml
  pallets/doctors/src/benchmarking.rs
  pallets/doctors/src/interface.rs
  pallets/doctors/src/lib.rs
  pallets/genetic-testing/benchmarking/Cargo.toml
  pallets/genetic-testing/benchmarking/src/lib.rs
  pallets/genetic-testing/src/interface.rs
  pallets/genetic-testing/src/lib.rs
  pallets/hospital-certifications/benchmarking/Cargo.toml
  pallets/hospital-certifications/benchmarking/src/lib.rs
  pallets/hospitals/Cargo.toml
  pallets/hospitals/src/benchmarking.rs
  pallets/hospitals/src/interface.rs
  pallets/hospitals/src/lib.rs
  pallets/labs/Cargo.toml
  pallets/labs/src/benchmarking.rs
  pallets/labs/src/interface.rs
  pallets/labs/src/lib.rs
  pallets/orders/benchmarking/Cargo.toml
  pallets/orders/benchmarking/src/lib.rs
  pallets/orders/src/lib.rs
  pallets/services/benchmarking/Cargo.toml
  pallets/services/benchmarking/src/lib.rs
  primitives/area-code/Cargo.toml
  primitives/area-code/src/lib.rs
  traits/genetic-testing/src/lib.rs
Labels: bug, Improvement

#150 tests: bench use escrow key as mock.
  Cargo.lock
  pallets/genetic-testing/benchmarking/Cargo.toml
  pallets/orders/benchmarking/Cargo.toml
  pallets/orders/benchmarking/src/lib.rs
  pallets/orders/benchmarking/src/mock.rs
  pallets/orders/src/weights.rs
Labels: bug, tests, Improvement

#151 fix: remove emr file extrinsic.
  pallets/electronic-medical-record/src/lib.rs
Labels: bug, Improvement

#152 ci: improve env for staging
  .github/workflows/alpha.yml
Labels: CI

#154 fix: transfer balance when finalizing request
  pallets/service-request/src/lib.rs
Labels: Improvement

#156 Added TestNet chain spec json raw
  resources/testnet.json
Labels: documentation

#157 Removed debio session keys on Testnet
  node/src/chain_spec.rs
Labels: Improvement

#158 Fixed chain-spec
  node/src/chain_spec.rs
Labels: bug

#161 ci: improve publish-draft-release
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
Labels: CI

#163 ci: create chain-spec.json improve
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI

#164 Updated chain-spec
  resources/testnet.json
Labels: enhancement

#165 added field created_at and updated_at in Request Struct
  pallets/service-request/src/lib.rs
Labels: Improvement

#168 Updated testnet chain-spec
  resources/testnet.json
Labels: Feature

#170 ci: improve rust cache
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI

#171 fix: region and city code.
  pallets/doctors/src/lib.rs
  pallets/hospitals/src/lib.rs
  pallets/labs/src/lib.rs
  primitives/area-code/src/lib.rs
Labels: bug

#172 feat: new param on create order.
  Cargo.lock
  pallets/genetic-testing/benchmarking/src/lib.rs
  pallets/orders/benchmarking/src/lib.rs
  pallets/orders/src/interface.rs
  pallets/orders/src/lib.rs
Labels: enhancement, Improvement

#144 feat: implement transfer funds.
  .maintain/benchmark.sh
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/orders/src/interface.rs
  pallets/orders/src/lib.rs
  pallets/rewards/Cargo.toml
  pallets/rewards/src/interface.rs
  pallets/rewards/src/lib.rs
  runtime/src/lib.rs
Labels: Improvement

#173 docs: pallet documentation.
  docs/pallets.md
Labels: documentation

#179 ci: use sccache for rust cache
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/mlc_config.json
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/rcb_config.json
  .github/workflows/release.yml
Labels: CI

#180 ci: improve injected-binnary.Dockerfile
  .maintain/docker/injected-binnary.Dockerfile
Labels: CI

#181 ci: docker build from cache
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#183 fix: clippy and fmt certification pallet
  pallets/certifications/src/interface.rs
  pallets/certifications/src/lib.rs
  pallets/certifications/src/weights.rs
Labels: Improvement

#185 ci: separate staging environment
  .github/workflows/alpha.yml
Labels: CI

#189 chore: updated resource chain-spec
  resources/testnet.json
Labels: Feature

#191 ci: improve build job
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#193 fixed pallet orders
  Cargo.lock
  pallets/orders/Cargo.toml
  pallets/orders/src/interface.rs
  pallets/orders/src/lib.rs
  pallets/orders/src/mock.rs
  pallets/orders/src/tests.rs
Labels: improvement
