Repository debionetwork/debio-node, pull requests merged in 2021-12, with the labels that each got.

#194 ci: renamed testnet env
  .github/workflows/beta.yml
Labels: CI

#197 feat: get pallet account id.
  node/src/chain_spec.rs
  pallets/rewards/src/lib.rs
Labels: enhancement, feature

#198 rerun benchmarking
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/src/weights/frame_system.rs
  runtime/src/weights/pallet_assets.rs
  runtime/src/weights/pallet_im_online.rs
  runtime/src/weights/pallet_timestamp.rs
Labels: help wanted

#200 chore: bump spec version to 103
  Cargo.lock
  node/src/chain_spec.rs
  resources/mainnet.json
  resources/testnet.json
  runtime/src/lib.rs
Labels: improvement

#201 feat: update chainspec
  node/src/chain_spec.rs
Labels: bug

#203 refactor: pallet Id defined at runtime.
  Cargo.lock
  node/src/chain_spec.rs
  pallets/rewards/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement, refactor

#204 chore: bump spec version to 104
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/rewards/src/mock.rs
  runtime/src/lib.rs
Labels: improvement

#206 feat: rewards pallet.
  Cargo.lock
  node/src/chain_spec.rs
  pallets/rewards/Cargo.toml
  pallets/rewards/src/benchmarking.rs
  pallets/rewards/src/interface.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/weights.rs
Labels: enhancement, feature

#208 added new benchmark for service request
  pallets/service-request/src/benchmarking.rs
Labels: improvement

#211 chore: bump spec version to 105
  runtime/src/lib.rs
Labels: feature

#217 fix typo staging network name
  node/src/chain_spec.rs
Labels: improvement

#218 ci: fixed typo
  .github/workflows/release.yml
Labels: CI

#222 ci: improve deploy dan draft release conditions
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#223 ci: fixed draft release conditions
  .github/workflows/main.yml
Labels: CI

#224 ci: improve build and deploy conditions
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: CI

#225 ci: fix deploy automatin typo
  .github/workflows/deploy.yml
Labels: CI

#226 ci: add trigger tag
  .github/workflows/main.yml
Labels: CI

#235 feat: remove requirement to set eth address.
  pallets/labs/src/lib.rs
Labels: improvement

#236 Updated weight template to avoid clippy
  .maintain/pallet-weight-template.hbs
Labels: improvement, refactor

#237 feat: change emr data structure for extrinsic.
  pallets/electronic-medical-record/src/benchmarking.rs
  pallets/electronic-medical-record/src/interface.rs
  pallets/electronic-medical-record/src/lib.rs
  pallets/electronic-medical-record/src/tests.rs
  pallets/rewards/src/benchmarking.rs
  traits/electronic-medical-record/src/lib.rs
Labels: tests, feature, refactor

#238 Bump spec version
  .maintain/docker/docker-compose.yml
  README.md
  node/res/.gitkeep
  node/res/octopus-mainnet.json
  node/res/octopus-testnet.json
  node/src/chain_spec.rs
  node/src/command.rs
  runtime/src/lib.rs
Labels: improvement
