Repository debionetwork/debio-node, pull requests merged in 2022-02, with the labels that each got.

#243 [DBIO-1684 & DBIO-1687] feat: genetic analyst and qualifications pallet.
  Cargo.lock
  pallets/genetic-analyst-qualifications/Cargo.toml
  pallets/genetic-analyst-qualifications/benchmarking/Cargo.toml
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/benchmarking/src/mock.rs
  pallets/genetic-analyst-qualifications/src/interface.rs
  pallets/genetic-analyst-qualifications/src/lib.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-qualifications/tests/Cargo.toml
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
  pallets/genetic-analyst-qualifications/tests/src/mock.rs
  pallets/genetic-analysts/Cargo.toml
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/interface.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/mock.rs
  pallets/genetic-analysts/src/tests.rs
  pallets/genetic-analysts/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  traits/genetic-analyst-qualifications/Cargo.toml
  traits/genetic-analyst-qualifications/src/lib.rs
Labels: enhancement, feature

#244 [DBIO-1686] tests: genetic analyst pallet unit tests.
  pallets/genetic-analysts/src/mock.rs
  pallets/genetic-analysts/src/tests.rs
Labels: tests

#247 [DBIO-1685] tests: genetic analyst pallet benchmarks.
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, tests

#245 [DBIO-1689] tests: genetic analyst qualifications pallet.
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
Labels: tests

#246 [DBIO-1688] tests: genetic analyst qualifications benchmark.
  Cargo.lock
  pallets/genetic-analyst-qualifications/benchmarking/Cargo.toml
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/benchmarking/src/mock.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, tests

#249 [DBIO-1694] tests: genetic analyst services unit tests.
  Cargo.lock
  pallets/genetic-analyst-services/tests/Cargo.toml
  pallets/genetic-analyst-services/tests/src/lib.rs
  pallets/genetic-analyst-services/tests/src/mock.rs
Labels: tests

#250 [DBIO-1693] tests: genetic analyst services benchmark.
  Cargo.lock
  pallets/genetic-analyst-services/benchmarking/Cargo.toml
  pallets/genetic-analyst-services/benchmarking/src/lib.rs
  pallets/genetic-analyst-services/benchmarking/src/mock.rs
  pallets/genetic-analyst-services/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, tests

#252 [DBIO-1708] feat: genetic data pallet.
  Cargo.lock
  pallets/genetic-data/Cargo.toml
  pallets/genetic-data/src/interface.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-data/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, feature

#253 [DBIO-1710] tests: genetic data unit tests.
  pallets/genetic-data/src/benchmarking.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-data/src/mock.rs
  pallets/genetic-data/src/tests.rs
  pallets/genetic-data/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: tests

#256 [DBIO-1716 & DBIO-1727] feat: genetic analysis orders pallet.
  Cargo.lock
  node/src/chain_spec.rs
  pallets/genetic-analysis-orders/Cargo.toml
  pallets/genetic-analysis-orders/src/interface.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/interface.rs
  pallets/genetic-analysis/src/lib.rs
  pallets/genetic-analysis/traits/src/lib.rs
  primitives/price-and-currency/src/lib.rs
  primitives/tracking-id/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, feature

#257 [DBIO-1721] tests: genetic analysis unit tests.
  Cargo.lock
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis/benchmarking/Cargo.toml
  pallets/genetic-analysis/benchmarking/src/lib.rs
  pallets/genetic-analysis/benchmarking/src/mock.rs
  pallets/genetic-analysis/src/lib.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analysis/tests/Cargo.toml
  pallets/genetic-analysis/tests/src/lib.rs
  pallets/genetic-analysis/tests/src/mock.rs
  pallets/genetic-analysis/traits/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: tests

#260 [DBIO-1718] tests: genetic analysis orders unit tests.
  pallets/genetic-analysis-orders/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/benchmarking/src/mock.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis-orders/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: tests

#261 [DBIO-1697 & DBIO-1698 & DBIO-1701] feat: genetic analyst staking and verification.
  Cargo.lock
  node/src/chain_spec.rs
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis/benchmarking/src/lib.rs
  pallets/genetic-analysis/tests/src/lib.rs
  pallets/genetic-analysis/tests/src/mock.rs
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
  pallets/genetic-analyst-qualifications/tests/src/mock.rs
  pallets/genetic-analyst-services/benchmarking/src/lib.rs
  pallets/genetic-analyst-services/tests/src/lib.rs
  pallets/genetic-analyst-services/tests/src/mock.rs
  pallets/genetic-analysts/Cargo.toml
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/interface.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/mock.rs
  pallets/genetic-analysts/src/tests.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-testing/tests/src/lib.rs
  primitives/verification-status/Cargo.toml
  primitives/verification-status/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement, feature

#266 [DBIO-1145] ci: add auto benchmark workflow
  .github/workflows/benchmark.yml
Labels: CI

#267 docs: status badge.
  README.md
Labels: documentation

#268 ci: improve sonar scan workflow
  .github/workflows/benchmark.yml
  .github/workflows/rcb_config.json
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: CI

#271 ci: change actions-rs version
  .github/workflows/benchmark.yml
Labels: CI

#272 ci: fix toolchain github runner self-hosted
  .github/workflows/benchmark.yml
Labels: CI

#273 feat: increment spec version and benchmarking
  Cargo.lock
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  runtime/src/lib.rs
Labels: feature

#275 docs: update badges
  .github/workflows/tester.yml
  README.md
Labels: documentation

#278 [DBIO-1802 & DBIO-1812] feat: genetic data timestamp.
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-data/src/tests.rs
Labels: enhancement

#280 [DBIO-1801 & DBIO-1816 & DBIO-1817] feat: add genetic data Id to genetic analysis orders.
  Cargo.lock
  pallets/genetic-analysis-orders/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/benchmarking/src/mock.rs
  pallets/genetic-analysis-orders/src/interface.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis/benchmarking/Cargo.toml
  pallets/genetic-analysis/benchmarking/src/lib.rs
  pallets/genetic-analysis/benchmarking/src/mock.rs
  pallets/genetic-analysis/tests/Cargo.toml
  pallets/genetic-analysis/tests/src/lib.rs
  pallets/genetic-analysis/tests/src/mock.rs
  pallets/genetic-data/Cargo.toml
  pallets/genetic-data/src/benchmarking.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-data/traits/Cargo.toml
  pallets/genetic-data/traits/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement, tests, feature

#281 [DBIO-1818] tests: update unit tests and benchmarks.
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/tests.rs
Labels: enhancement, tests

#282 [DBIO-1804, DBIO-1805, DBIO-1806, DBIO-1807, DBIO-1808, DBIO-1809 & DBIO-1819] feat: update admin key extrinsic.
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/src/interface.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/tests.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/benchmarking.rs
  pallets/labs/src/interface.rs
  pallets/labs/src/lib.rs
  pallets/labs/src/tests.rs
  pallets/labs/src/weights.rs
  pallets/orders/benchmarking/src/lib.rs
  pallets/orders/src/interface.rs
  pallets/orders/src/lib.rs
  pallets/orders/src/tests.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/benchmarking.rs
  pallets/rewards/src/interface.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/benchmarking.rs
  pallets/service-request/src/interface.rs
  pallets/service-request/src/lib.rs
  pallets/service-request/src/mock.rs
  pallets/service-request/src/tests.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/benchmarking.rs
  pallets/user-profile/src/interface.rs
  pallets/user-profile/src/lib.rs
  pallets/user-profile/src/tests.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
Labels: enhancement, tests, feature

#279 feat: benchmarking
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
Labels: feature

#283 [DBIO-1825] feat : add field in genetic analyst pallet
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis/benchmarking/src/lib.rs
  pallets/genetic-analysis/tests/src/lib.rs
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
  pallets/genetic-analyst-services/benchmarking/src/lib.rs
  pallets/genetic-analyst-services/tests/src/lib.rs
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/tests.rs
Labels: enhancement, tests, feature

#284 fix: order failed emit.
  pallets/genetic-analysis/src/lib.rs
Labels: bug

#285 [DBIO-1716]: feat: ga orders escrow.
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/benchmarking/src/mock.rs
  pallets/genetic-analysis/tests/src/mock.rs
  pallets/genetic-analyst-services/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement, tests, feature

#289 tests: update unit tests.
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/mock.rs
  pallets/genetic-analysts/src/tests.rs
Labels: tests, refactor

#290 fix: genetic analyst services prices.
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analyst-services/src/lib.rs
Labels: bug

#291 [DBIO-1882] feat: genetic analyst box public key.
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/benchmarking/src/lib.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analysis/tests/src/lib.rs
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
  pallets/genetic-analyst-services/benchmarking/src/lib.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analyst-services/tests/src/lib.rs
  pallets/genetic-analysts/src/benchmarking.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/tests.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
Labels: enhancement, test, refactor

#292 Benchmarking
  node/Cargo.toml
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature

#293 [DBIO-1893] feat : upload wasm file to discord
  .github/workflows/builder.yml
Labels: ci

#295 feat: benchmarking
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
Labels: ci

#296 Update octopus-pallets and bump spec_version to 119
  Cargo.lock
  runtime/src/lib.rs
Labels: feature
