Repository debionetwork/debio-node, pull requests merged in 2022-07, with the labels that each got.

#324 feat: move 5% fees to treasury wallet
  node/src/chain_spec.rs
  pallets/genetic-analysis-orders/benchmarking/src/lib.rs
  pallets/genetic-analysis-orders/src/interface.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysis-orders/src/weights.rs
Labels: enhancement, test, feature

#325 fix: bad signature error on retrieve unstake
  Cargo.lock
  pallets/genetic-analysis-orders/Cargo.toml
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysts/Cargo.toml
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/tests/src/lib.rs
  pallets/labs/Cargo.toml
  pallets/labs/src/lib.rs
  pallets/labs/tests/src/lib.rs
  pallets/service-request/src/lib.rs
  pallets/service-request/src/tests.rs
Labels: fix, test

#326 feat: bump version to 2.1.2
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature

#327 fix: final request bad signature error
  Cargo.lock
  pallets/service-request/src/lib.rs
Labels: fix

#329 feat: bump version to 2.1.3
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: ci

#331 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#333 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#334 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#330 feat: registered account id in user profile pallet
  .maintain/pallet-weight-template.hbs
  Cargo.lock
  node/Cargo.toml
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/benchmarking.rs
  pallets/user-profile/src/interface.rs
  pallets/user-profile/src/lib.rs
  pallets/user-profile/src/tests.rs
  pallets/user-profile/src/weights.rs
  pallets/user-profile/traits/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: fix, test, ci, improvement, feature, refactor

#335 fix: bump version to 2.1.2
  Cargo.lock
Labels: fix
