Repository debionetwork/debio-node, pull requests merged in 2022-03, with the labels that each got.

#297 feat: bulk create genetic analyst services.
  .github/pull_request_template.md
  .github/workflows/mlc_config.json
  pallets/genetic-analyst-services/benchmarking/src/lib.rs
  pallets/genetic-analyst-services/src/interface.rs
  pallets/genetic-analyst-services/src/lib.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analyst-services/tests/src/lib.rs
Labels: enhancement, test

#298 feat: bulk create genetic analyst qualifications.
  pallets/genetic-analyst-qualifications/benchmarking/src/lib.rs
  pallets/genetic-analyst-qualifications/src/interface.rs
  pallets/genetic-analyst-qualifications/src/lib.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-qualifications/tests/src/lib.rs
Labels: enhancement, test

#300 fix : update spec_version from 119 to 120
  runtime/src/lib.rs
Labels: fix

#301 feat: retrieve unstake amount extrinsic and availability status default.
  pallets/genetic-analysis-orders/src/tests.rs
  pallets/genetic-analysts/benchmarking/src/lib.rs
  pallets/genetic-analysts/src/interface.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-analysts/tests/src/lib.rs
  primitives/availability-status/src/lib.rs
Labels: enhancement, test

#302 fix: bump spec_version to 121
  runtime/src/lib.rs
Labels: fix

#303 Update to a new set of bootnodes
  node/res/octopus-mainnet.json
  node/res/octopus-testnet.json
Labels: improvement

#305 [DBIO-2223] ci: google auth with workload identity federation
  .github/workflows/benchmark.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: ci

#306 ci: fix typo
  .github/workflows/deployer.yml
Labels: ci

#307 ci: fix typo
  .github/workflows/deployer.yml
Labels: ci

#304 feat: enhance unstake
  .maintain/install-hooks.sh
  Cargo.lock
  Makefile
  docs/pallets.md
  docs/pallets/certifications.md
  docs/pallets/doctor-certifications.md
  docs/pallets/doctors.md
  docs/pallets/electronic-medical-record.md
  docs/pallets/genetic-analysis-orders.md
  docs/pallets/genetic-analysis.md
  docs/pallets/genetic-analyst-qualifications.md
  docs/pallets/genetic-analyst-services.md
  docs/pallets/genetic-analysts.md
  docs/pallets/genetic-data.md
  docs/pallets/genetic-testing.md
  docs/pallets/hospital-certifications.md
  docs/pallets/hospitals.md
  docs/pallets/labs.md
  docs/pallets/orders.md
  docs/pallets/rewards.md
  docs/pallets/service-request.md
  docs/pallets/services.md
  docs/pallets/user-profile.md
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analysts/Cargo.toml
  pallets/genetic-analysts/benchmarking/src/lib.rs
  pallets/genetic-analysts/src/interface.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/migrations.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-analysts/tests/src/lib.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
Labels: enhancement, test, feature

#308 feat: benchmarking & bump spec_version to 122
  pallets/certifications/src/weights.rs
  pallets/doctor-certifications/src/weights.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/weights.rs
  pallets/genetic-analysis/src/weights.rs
  pallets/genetic-analyst-qualifications/src/weights.rs
  pallets/genetic-analyst-services/src/weights.rs
  pallets/genetic-analysts/src/weights.rs
  pallets/genetic-data/src/weights.rs
  pallets/genetic-testing/src/weights.rs
  pallets/hospital-certifications/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/labs/src/weights.rs
  pallets/orders/src/weights.rs
  pallets/rewards/src/weights.rs
  pallets/service-request/src/weights.rs
  pallets/services/src/weights.rs
  pallets/user-profile/src/weights.rs
  runtime/src/lib.rs
Labels: feature
