Repository debionetwork/debio-node, pull requests merged in 2022-09, with the labels that each got.

#348 feat: add profile roles to customer registration
  pallets/certifications/src/lib.rs
  pallets/doctor-certifications/src/lib.rs
  pallets/doctors/src/lib.rs
  pallets/electronic-medical-record/src/lib.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis/src/lib.rs
  pallets/genetic-analyst-qualifications/src/lib.rs
  pallets/genetic-analyst-services/src/lib.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-data/src/lib.rs
  pallets/genetic-testing/src/lib.rs
  pallets/hospital-certifications/src/lib.rs
  pallets/hospitals/src/lib.rs
  pallets/labs/src/lib.rs
  pallets/orders/src/lib.rs
  pallets/services/src/lib.rs
  pallets/user-profile/src/interface.rs
  pallets/user-profile/src/lib.rs
  pallets/user-profile/src/tests.rs
Labels: duplicate, enhancement, feature

#350 feat: add USN and USDT assets options for payment
  .maintain/install-hooks.sh
  Cargo.lock
  Makefile
  pallets/genetic-analysis-orders/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/Cargo.toml
  pallets/genetic-analysis-orders/benchmarking/src/mock.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-analysis/benchmarking/Cargo.toml
  pallets/genetic-analysis/benchmarking/src/mock.rs
  pallets/genetic-analysis/tests/Cargo.toml
  pallets/genetic-analysis/tests/src/mock.rs
  pallets/genetic-analyst-qualifications/tests/Cargo.toml
  pallets/genetic-analyst-qualifications/tests/src/mock.rs
  pallets/genetic-analyst-services/tests/Cargo.toml
  pallets/genetic-analyst-services/tests/src/lib.rs
  pallets/genetic-analyst-services/tests/src/mock.rs
  pallets/genetic-analysts/Cargo.toml
  pallets/genetic-analysts/benchmarking/Cargo.toml
  pallets/genetic-analysts/benchmarking/src/mock.rs
  pallets/genetic-analysts/tests/Cargo.toml
  pallets/genetic-analysts/tests/src/mock.rs
  primitives/price-and-currency/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement, feature

#353 chore: bump version to 2.1.5
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#351 feat: add menstrual calendar data
  .maintain/run-benchmark-locally-build-once.sh
  Cargo.lock
  Makefile
  node/src/chain_spec.rs
  pallets/doctors/src/weights.rs
  pallets/electronic-medical-record/src/weights.rs
  pallets/genetic-analysis-orders/src/mock.rs
  pallets/genetic-data/src/weights.rs
  pallets/hospitals/src/weights.rs
  pallets/menstrual-calendar/Cargo.toml
  pallets/menstrual-calendar/src/benchmarking.rs
  pallets/menstrual-calendar/src/interface.rs
  pallets/menstrual-calendar/src/lib.rs
  pallets/menstrual-calendar/src/mock.rs
  pallets/menstrual-calendar/src/tests.rs
  pallets/menstrual-calendar/src/weights.rs
  pallets/menstrual-calendar/traits/Cargo.toml
  pallets/menstrual-calendar/traits/src/lib.rs
  pallets/menstrual-subscription/Cargo.toml
  pallets/menstrual-subscription/src/benchmarking.rs
  pallets/menstrual-subscription/src/interface.rs
  pallets/menstrual-subscription/src/lib.rs
  pallets/menstrual-subscription/src/mock.rs
  pallets/menstrual-subscription/src/tests.rs
  pallets/menstrual-subscription/src/weights.rs
  pallets/menstrual-subscription/traits/Cargo.toml
  pallets/menstrual-subscription/traits/src/lib.rs
  pallets/user-profile/src/lib.rs
  pallets/user-profile/src/tests.rs
  pallets/user-profile/src/weights.rs
  primitives/duration/src/lib.rs
  primitives/menstrual-status/Cargo.toml
  primitives/menstrual-status/src/lib.rs
  primitives/price-and-currency/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, feature

#352 fix: allow Sudo to change admin key in pallet service_request
  pallets/service-request/src/functions.rs
  pallets/service-request/src/impl_service_request.rs
  pallets/service-request/src/interface.rs
  pallets/service-request/src/lib.rs
  pallets/service-request/src/tests.rs
  pallets/service-request/src/types.rs
Labels: improvement

#354 feat: payment service request with appchain token
  Cargo.lock
  pallets/service-request/Cargo.toml
  pallets/service-request/benchmarking/Cargo.toml
  pallets/service-request/benchmarking/src/lib.rs
  pallets/service-request/benchmarking/src/mock.rs
  pallets/service-request/src/functions.rs
  pallets/service-request/src/impl_service_request.rs
  pallets/service-request/src/interface.rs
  pallets/service-request/src/lib.rs
  pallets/service-request/src/migrations.rs
  pallets/service-request/src/mock.rs
  pallets/service-request/src/tests.rs
  pallets/service-request/src/types.rs
  runtime/src/lib.rs
Labels: feature

#356 fix: change to customer when setGeneticAnalysisOrderPaid
  pallets/genetic-analysis-orders/src/interface.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
Labels: improvement

#355 feat: move smart contract logic for request test to substrate
  Cargo.lock
  pallets/certifications/tests/Cargo.toml
  pallets/certifications/tests/src/mock.rs
  pallets/genetic-analyst-services/src/lib.rs
  pallets/genetic-analyst-services/src/migrations.rs
  pallets/genetic-testing/benchmarking/src/lib.rs
  pallets/genetic-testing/benchmarking/src/mock.rs
  pallets/genetic-testing/src/lib.rs
  pallets/genetic-testing/tests/Cargo.toml
  pallets/genetic-testing/tests/src/lib.rs
  pallets/genetic-testing/tests/src/mock.rs
  pallets/labs/benchmarking/Cargo.toml
  pallets/labs/benchmarking/src/mock.rs
  pallets/labs/tests/Cargo.toml
  pallets/labs/tests/src/lib.rs
  pallets/labs/tests/src/mock.rs
  pallets/orders/Cargo.toml
  pallets/orders/benchmarking/Cargo.toml
  pallets/orders/benchmarking/src/lib.rs
  pallets/orders/benchmarking/src/mock.rs
  pallets/orders/src/functions.rs
  pallets/orders/src/impl_orders.rs
  pallets/orders/src/interface.rs
  pallets/orders/src/lib.rs
  pallets/orders/src/migrations.rs
  pallets/orders/src/mock.rs
  pallets/orders/src/tests.rs
  pallets/orders/src/types.rs
  pallets/orders/traits/src/lib.rs
  pallets/service-request/benchmarking/src/mock.rs
  pallets/service-request/src/mock.rs
  pallets/services/benchmarking/Cargo.toml
  pallets/services/benchmarking/src/mock.rs
  pallets/services/src/functions.rs
  pallets/services/src/impl_services.rs
  pallets/services/src/interface.rs
  pallets/services/src/lib.rs
  pallets/services/src/migrations.rs
  pallets/services/src/types.rs
  pallets/services/tests/Cargo.toml
  pallets/services/tests/src/mock.rs
  primitives/price-and-currency/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: improvement, feature
