Repository debionetwork/debio-node, pull requests merged in 2022-08, with the labels that each got.

#337 chore: bump version to 2.1.3
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature

#339 feat: fixed dev chain spec
  Cargo.lock
  node/Cargo.toml
  node/res/dev-testnet.json
  node/src/chain_spec.rs
  node/src/command.rs
Labels: feature

#340 ci: remove session key injection
  .github/workflows/benchmark.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: ci

#341 chore: dump version to 2.1.3
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature

#342 ci: fixed docker builder
  .github/workflows/builder.yml
Labels: ci

#344 ci: fix tester filter
  .github/workflows/tester.yml
Labels: ci

#343 feat: update to v0.9.18-2
  Cargo.lock
  Makefile
  node/Cargo.toml
  pallets/labs/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#345 fix: pallet account id after runtime upgrade
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/migrations.rs
  pallets/genetic-analysts/src/lib.rs
  pallets/genetic-analysts/src/migrations.rs
  pallets/labs/src/lib.rs
  pallets/labs/src/migrations.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/migrations.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: fix

#346 fix: on null value pallet migration
  Cargo.lock
  node/Cargo.toml
  pallets/genetic-analysis-orders/src/migrations.rs
  pallets/genetic-analysts/src/migrations.rs
  pallets/labs/src/migrations.rs
  pallets/rewards/src/migrations.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: fix

#347 fix: getting storage version for continues update
  Cargo.lock
  node/Cargo.toml
  pallets/genetic-analysts/src/migrations.rs
  pallets/labs/src/migrations.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: fix
