Repository debionetwork/debio-node, pull requests merged in 2022-06, with the labels that each got.

#320 ci: improve deployments
  .github/workflows/deployer.yml
Labels: ci

#322 ci: add sleuth webhook
  .github/workflows/benchmark.yml
  .github/workflows/deployer.yml
Labels: ci

#321 fix: pending order bug
  pallets/genetic-analysis-orders/src/lib.rs
  pallets/genetic-analysis-orders/src/tests.rs
Labels: fix, test

#323 feat: bump version to 2.1.1
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature
